### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by Yes-Jumby** [sxyu/nerfvis#2]
>>> import nerfvis
>>> scene = nerfvis.Scene("My title")
>>> scene.add_cube("Cube1", color=[1.0, 0.0, 0.0], translation=[-1.0, -1.0, 0.0])
>>> scene.display(url='10.255.26.23',port=8020)

【jupyter can accessed it,but nerfvis cannot access it:(】
then there is error:
Serving localhost:8020
----------------------------------------
Exception happened during processing of request from ('172.24.142.99', 64624)
Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/conda/envs/py36/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/opt/conda/envs/py36/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/nerfvis/scene.py", line 840, in __init__
    super().__init__(*args, directory=dirname, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'directory'

please show me how to solve it

**Comment by ZMY666777** [comment]
> 

Hello, I meet the same question and find that you can solve this by updating your python version from 3.6 to 3.8. But I don't know if this is the only way to solve this problem.

**Comment by sxyu** [comment]
This seems to be some internal change in python's library SimpleHTTPRequestHandler added in python 3.7.
So it will work with python3.7 +..
